- Adding Dell-EMC OpenSwitch SAI 0.96+ implementation
open-switch/SAI pull request #1
Opened 2017-06-29 22:26 UTC by atanu-mandal

- Adding support for SAI debian packaging for use with OpenSwitch installation

2017-06-29 22:36 UTC, johntconklin requested changes

2017-06-29 22:36 UTC, johntconklin commented on inc/saiwred.h
> +
I'm not signing off on this review, as removing the Microsoft copyright seems very wrong to me.  Please confirm with legal types.

2017-06-29 22:37 UTC, atanu-mandal commented on inc/saiwred.h
> +
Can we add both Microsoft and Dell-EMC copyrights into this. Please confirm.

2017-06-30 02:53 UTC, atanu-mandal commented on inc/saiwred.h
> +
Corrected the error, added the Microsoft copyright back.

2017-07-05 22:57 UTC, merged